# Uncomment this line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

target "BiereBeacons" do

pod 'MBProgressHUD', '~> 0.8'
pod 'Masonry'

end

target "BiereBeaconsTests" do

pod 'Kiwi'

end